project:
  type: website
  output-dir: _site

website:
  title: "Actividad 02 — Portafolios Óptimos"
  navbar:
    title: "Reporte de Portafolios"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    embed-resources: true
    code-fold: true
    code-summary: "Ver código"
    fig-width: 10
    fig-height: 6

execute:
  echo: true
  warning: false
  message: false
