project:
  type: website
  output-dir: docs

# Finanzas en R - Course Website
website:
  title: "Curso Finanzas en R"
  site-url: https://sebaegana.github.io/finanzas_en_r_webpage/
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Clases"
        file: clases/index.qmd
      - text: "Clases con IA"
        file: clases_ia/index.qmd
      - text: "Recursos"
        href: recursos.qmd
      - text: "Contacto"
        href: contacto.qmd

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto


